name: Verademo-Pipeline

on: [push]

jobs:
  build-pipelinescan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify

    - name: Download the Veracode Pipeline Scan
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    
    - name: Unzip the Veracode Pipeline Scan
      run: unzip pipeline-scan-LATEST.zip pipeline-scan.jar
 
    - name: Run Veracode Pipeline Scan
      run: java -jar pipeline-scan.jar -f /home/runner/work/Verademo-master/Verademo-master/target/verademo.war -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_SECRET}}" --fail_on_severity="Very High, High" -jo true
      continue-on-error: true      

    - uses: actions/upload-artifact@v1
      with:
        name: ScanResults
        path: results.json

    - name: Convert pipeline scan output to SARIF format 
      id: convert
      uses: veracode/veracode-pipeline-scan-results-to-sarif@master
      with:
        pipeline-results-json: results.json
    - uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: veracode-results.sarif
