name: Verademo-ABS

on: [push]

jobs:
  abs-opensource-scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify
    - name: Download the Agent Based SCA Scanner
      env: # Set the secret as an input
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        SRCCLR_SCM_TYPE: GITHUB
        SRCCLR_SCM_TOKEN: ${{ secrets.SCM_GITHUB }} 
        SRCCLR_PR_ON: medium
        SRCCLR_NO_BREAKING_UPDATES: true
        SRCCLR_IGNORE_CLOSED_PRS: false
        SRCCLR_SCM_URL: https://github.com/christyson/Verademo-master
        EXTRA_ARGS: '--update-advisor --pull-request'
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan $EXTRA_ARGS
