name: Verademo-ABS

on: [push]

jobs:
  abs-opensource-scan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify
    - name: Download the Agent Based SCA Scanner
      env: # Set the secret as an input
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh
